### ISSUE TITLE
[Help Requested] New Contact Created

### ISSUE THREAD

**Issue by hamboneZA** [3sd/civicrm-sms-conversation#10]
Right, so I'm slowly getting to grips with this. I have my SMS provider set as Telerivit, messages are now sending - both scheduled and on a contact-by-contact basis. 

Incoming messages are being recorded, but they're not 'matching' with the contact?

Each time an incoming SMS comes from Telerivit it creates a brand new contact with 27840000000@mobile.sms as the e-mail, fills the Home Mobile field with the correctly formatted +27 84 000 0000 mobile number (is it appears on the contact that the outbound message was sent to) and an Inbound SMS with the details of the SMS that was sent.

So, it's almost as if CiviCRM doesn't know what to do with the SMS once it receives it, and makes a new contact.

Any ideas?

**Comment by mattwire** [comment]
@hamboneZA Have a look at the function processInbound() in CRM/SMS/Provider.php here: https://github.com/civicrm/civicrm-core/blob/master/CRM/SMS/Provider.php#L205

That should give you an idea where it is going wrong.

**Comment by hamboneZA** [comment]
@mattwire Sure, that explains in technical terms where things are going wrong - but I'm afraid you'll need to be far more explicit with a solution - it's been a long day! 

The question remains, how would one resolve the issue so as to ensure the Inbound SMS matches the right contact.

At first I thought it was duplicates. For some replies it might have been (that conversation for another day); but then I found a contact with no duplicate number and still, a new contact was created.

**Comment by mattwire** [comment]
@hamboneZA Did you work out what is actually going wrong? I didn't look into it, but sms conversations only takes over once CiviCRM has matched the sms to a contact ID so any fix/change would need to be in core I think!  Or contact metadata changes (eg. phone type)

**Comment by michaelmcandrew** [comment]
@hamboneZA - @mattwire is right in that the issue is (most likely) with core. your issue might be similar to one that we have experienced in the UK where the SMS provider reports the phone number in a different format to how it is stored in CiviCRM. For example, My number might be stored as 07777 123456 but the message comes back from the provider as 447777123456. IIRC / looking at the function that Matthew referenced, and also https://github.com/civicrm/civicrm-core/blob/master/CRM/SMS/Provider.php#L290 stripPhone(), CiviSMS strips many of the characters, but doesn't handle international codes fantastically.

You might want to play around with different numbers with / without international codes and also look at options in telerivet for how it reports back numbers.

You might find the dummy sms extension https://github.com/3sd/io.3sd.dummysms/ a useful debugging tool.

Michael

**Comment by hamboneZA** [comment]
Cheers lads, 

I've asked the Telerivet folk to point me towards some documentation that explains how their webhook API returns the return sender's number. If it means I go and do some record cleaning in CiviCRM to conform to their reported number, that's a win.

The alternative might be altering this extensions' number formatting validation rule - one which I'd rather avoid as I've no idea how many iterations there are of it?

[FYI] Our numbers are stored on CiviCRM as +CC NN 000 0000 where CC is the country code, and NN is the network prefix.

Appreciate the tips here - catch up when I've some feedback from Telerivet.

**Comment by hamboneZA** [comment]
> The from_number parameter uses the format provided by the mobile network -- most mobile networks use E.164 format but some don't. In that case, you can use the from_number_e164 parameter: https://telerivet.com/api/webhook#incoming_message
- Telerivet Support

**Comment by michaelmcandrew** [comment]
My hunch is that the answer is likely to either be a contribution to the core SMS processor, or an extension that does some cleaning of south african numbers (seperate from telerivet).

I don't think that it belongs in this repo so unless you think otherwise, I'll close the ticket.
